In [1]:
import pandas as pd

In [2]:
FILENAME = 'kingdeedata.xlsx'

In [3]:
df = pd.read_excel(FILENAME)

In [8]:
df.head()
from math import isnan

In [13]:
dates = df['Date'].tolist()
current_date = dates[0]
pointer = 0
for index, date in enumerate(dates):
    #if it is a datetime, isnan will fail and except branch is triggered.
    try:
        isnan(date)
        dates[index] = current_date  
    except:
        current_date = date

df['Date'] = dates
df.head()

,Date,FY,FP,Voucher Category,Voucher No.,Description,Account Code,Full Account Name,Currency,Amount (Original Currency),...,Credit Amount,Prepared by,Approved by,Post,Cashier,Source System,Business Type,Approving Status,Voiding Status,Attachment Qty
0,2023-04-17 00:00:00,2023.0,4.0,JV,71.0,"SIDLEY AUSTIN LLP,For professional services re...",1800.0002,Loans & Other Receivable_Cayman 1,USD,1671.75,...,NaN,Jane Tse,Mike Fan,Mike Fan,NaN,G/L,Manually Input,Approved,Normal,1.0
1,2023-04-17 00:00:00,NaN,NaN,NaN,NaN,"SIDLEY AUSTIN LLP,For professional services re...",1002.0008,Bank_Cash in Checking - Chase-1201,USD,1671.75,...,1671.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-06-15 00:00:00,2023.0,6.0,JV,2.0,"Wellpros Consultancy Limited,preparing annual ...",5602.0013,General Administrative Expense_Legal & Profess...,HKD,9105.00,...,NaN,Jane Tse,Mike Fan,Mike Fan,NaN,G/L,Manually Input,Approved,Normal,1.0
3,2023-06-15 00:00:00,NaN,NaN,NaN,NaN,"Wellpros Consultancy Limited,preparing annual ...",2202.0001,Accounts Payable_Vendor,HKD,9105.00,...,9105.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-06-29 00:00:00,2023.0,6.0,JV,3.0,"HK CBT Payment on behalf of HK Pharma,Wellpros...",2202.0001,Accounts Payable_Vendor,HKD,9105.00,...,NaN,Jane Tse,Mike Fan,Mike Fan,NaN,G/L,Manually Input,Approved,Normal,0.0

In [14]:
df.head(15)

,Date,FY,FP,Voucher Category,Voucher No.,Description,Account Code,Full Account Name,Currency,Amount (Original Currency),...,Credit Amount,Prepared by,Approved by,Post,Cashier,Source System,Business Type,Approving Status,Voiding Status,Attachment Qty
0,2023-04-17 00:00:00,2023.0,4.0,JV,71.0,"SIDLEY AUSTIN LLP,For professional services re...",1800.0002,Loans & Other Receivable_Cayman 1,USD,1671.75,...,NaN,Jane Tse,Mike Fan,Mike Fan,NaN,G/L,Manually Input,Approved,Normal,1.0
1,2023-04-17 00:00:00,NaN,NaN,NaN,NaN,"SIDLEY AUSTIN LLP,For professional services re...",1002.0008,Bank_Cash in Checking - Chase-1201,USD,1671.75,...,1671.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-06-15 00:00:00,2023.0,6.0,JV,2.0,"Wellpros Consultancy Limited,preparing annual ...",5602.0013,General Administrative Expense_Legal & Profess...,HKD,9105.00,...,NaN,Jane Tse,Mike Fan,Mike Fan,NaN,G/L,Manually Input,Approved,Normal,1.0
3,2023-06-15 00:00:00,NaN,NaN,NaN,NaN,"Wellpros Consultancy Limited,preparing annual ...",2202.0001,Accounts Payable_Vendor,HKD,9105.00,...,9105.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-06-29 00:00:00,2023.0,6.0,JV,3.0,"HK CBT Payment on behalf of HK Pharma,Wellpros...",2202.0001,Accounts Payable_Vendor,HKD,9105.00,...,NaN,Jane Tse,Mike Fan,Mike Fan,NaN,G/L,Manually Input,Approved,Normal,0.0
5,2023-06-29 00:00:00,NaN,NaN,NaN,NaN,"HK CBT Payment on behalf of HK Pharma,Wellpros...",2200.0004,Loans Payable_HK CBT,HKD,9105.00,...,9105.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2023-01-01 00:00:00,2023.0,1.0,JV,4.0,"Maples and Calder (Hong Kong) LLP,2023 Annual ...",5602.0013,General Administrative Expense_Legal & Profess...,USD,3219.51,...,NaN,Jane Tse,Mike Fan,Paul Fung,NaN,G/L,Manually Input,Approved,Normal,1.0
7,2023-01-01 00:00:00,NaN,NaN,NaN,NaN,"Maples and Calder (Hong Kong) LLP,2023 Annual ...",2202.0001,Accounts Payable_Vendor,USD,3219.51,...,3219.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2023-01-01 00:00:00,NaN,NaN,NaN,NaN,"Maples and Calder (Hong Kong) LLP,Legal Fees a...",5602.0013,General Administrative Expense_Legal & Profess...,USD,6035.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2023-01-01 00:00:00,NaN,NaN,NaN,NaN,"Maples and Calder (Hong Kong) LLP,Legal Fees a...",2202.0001,Accounts Payable_Vendor,USD,6035.00,...,6035.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2023-02-09 00:00:00,2023.0,2.0,JV,4.0,"Maples and Calder (Hong Kong) LLP,Attend on Re...",5602.0013,General Administrative Expense_Legal & Profess...,USD,413.66,...,NaN,Jane Tse,Mike Fan,Paul Fung,NaN,G/L,Manually Input,Approved,Normal,1.0
11,2023-02-09 00:00:00,NaN,NaN,NaN,NaN,"Maples and Calder (Hong Kong) LLP,Attend on Re...",2202.0001,Accounts Payable_Vendor,USD,413.66,...,413.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2023-03-21 00:00:00,2023.0,3.0,JV,2.0,"HK CBT Payment on half of Cayman2, Maples and ...",2202.0001,Accounts Payable_Vendor,USD,9668.17,...,NaN,Jane Tse,Mike Fan,Paul Fung,NaN,G/L,Manually Input,Approved,Normal,0.0
13,2023-03-21 00:00:00,NaN,NaN,NaN,NaN,"HK CBT Payment on half of Cayman2, Maples and ...",2200.0004,Loans Payable_HK CBT,USD,9668.17,...,9668.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2023-05-05 00:00:00,2023.0,5.0,JV,3.0,"Maples and Calder (Hong Kong) LLP,Cayman Islan...",5602.0013,General Administrative Expense_Legal & Profess...,USD,6416.94,...,NaN,Jane Tse,Mike Fan,Paul Fung,NaN,G/L,Manually Input,Approved,Normal,2.0